{
  version: '3',
  services: {
    application: {
      image: asp-net-core,
      ports: [
        "8085:80"
      ],
      build: {
        context: ./,
        dockerfile: Dockerfile,
      },
      networks: [
        mongodb-network
      ]
    }
  },
  networks: {
    mongodb-network: {
      external: {
        name: mongodb-network
      }
    }
  }
}